### ISSUE TITLE
Trencher not trenching

### ISSUE THREAD

**Issue by montecuccoli1** [Seb105/Arma-Trencher#1] opened 2024-05-29 15:50 UTC
Trenches will not appear despite saving, and when I go back to editor Arma crashes. This happens both with my usual modpack and with just trencher & dependencies loaded. 

Steps to reproduce:
1) place Trench Controller
2) place Trench Pieces left and right of it, sync with controller 
3) place playable unit
4) save mission
5) play mission
6) ??? no trenches

**Comment by Seb105** [comment] 2024-05-29 17:31
I can't reproduce this following your steps.

Can you post a pic of what you've got in the editor before preview, and also your [.rpt](https://community.bistudio.com/wiki/arma.RPT) file after your game has crashed

**Comment by montecuccoli1** [comment] 2024-05-29 17:45
After restarting the PC it seems to work, no crash on return to editor. This was my exact setup even earlier, no idea what made it work this time around. I attached the crash report anyway

[crashreport.txt](https://github.com/Seb105/Arma-Trencher/files/15488724/crashreport.txt)

![20240529193704_1](https://github.com/Seb105/Arma-Trencher/assets/171169918/4e010fa2-7552-4d2f-9d29-b8170ab13306)
![20240529193804_1](https://github.com/Seb105/Arma-Trencher/assets/171169918/a670dfee-6d2b-4d84-8094-b29fcec11ade)

**Comment by Seb105** [comment] 2024-05-29 17:56
If I had to guess I'd say a dependency didn't load correctly, but your .rpt looks fine. I'll leave this issue open for a bit to see if anyone else has the same issue

**Comment by M113-ITV** [comment] 2024-05-30 17:42
I've had the same problem with the Trenches not Trenching in game. It tends to happen when you disable the "Bend Trench Ends" Option in the Control Module. I've included my .rpt file. Game always freezes when trying to return to the editor after playing a mission.
[Arma3_x64_2024-05-30_10-46-43.txt](https://github.com/Seb105/Arma-Trencher/files/15503760/Arma3_x64_2024-05-30_10-46-43.txt)

**Comment by Seb105** [comment] 2024-05-30 23:39
The freezing is a separate issue Ive just fixed, but the blend trench ends option being the culprit for other issues is some good info

**Comment by TheD00MSlayer** [comment] 2024-05-31 03:38
Same issue here with the Trenches not Trenching in game. It's also the same issue for me when I disable the "Blend Trench Ends" option. If I leave the trench blend edge option enabled the terrain is deformed with no issues but disabling this option makes the terrain not deform.

**Comment by Seb105** [comment] 2024-06-06 23:30
fixed in 1.4, turns out profiling branch has commands stable doesnt!

**Closed as completed** 2024-06-06 23:30 UTC
